name: CI and Auto-Pachyderm Pipeline Update

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PACHYDERM_CLUSTER_URL: https://hub-c0-muzo11nd02.clusters.pachyderm.io:31400
      PACHYDERM_TOKEN: ${{ secrets.PACHYDERM_TOKEN }}
      DOCKER_IMAGE_NAME: jimmywhitaker/market_sentiment
      PACHYDERM_PIPELINE_FILES: pachyderm/dataset.json pachyderm/train_model.json

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_TOKEN }}' | docker login --username '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin

      # Build docker image
      - name: Build the tagged Docker image
        run: docker build --tag ${DOCKER_IMAGE_NAME}:${GITHUB_SHA} .
      
      # Push image to Docker Hub
      - name: Push docker image
        run: docker push ${DOCKER_IMAGE_NAME}:${GITHUB_SHA}
      
      # Update Pachyderm Pipelines
      - name: pachyderm-update-pipelines
        uses: ./pachyderm-github-action
        id: pup
