name: CI and Auto-Pachyderm Pipeline Update

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python-ci: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run unit tests
      run: pytest tests/ -vv -s

  # This workflow contains the docker build and Pachyderm Update
  build:
    # Wait for CI to finish before building and pushing
    needs: python-ci
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PACHYDERM_CLUSTER_URL: https://hub-c0-muzo11nd02.clusters.pachyderm.io:31400
      PACHYDERM_TOKEN: ${{ secrets.PACHYDERM_TOKEN }}
      DOCKER_IMAGE_NAME: jimmywhitaker/market_sentiment
      PACHYDERM_PIPELINE_FILES: pachyderm/dataset.json pachyderm/train_model.json pachyderm/visualizations.json

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_TOKEN }}' | docker login --username '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin

      # Build docker image
      - name: Build the tagged Docker image
        run: docker build --tag ${DOCKER_IMAGE_NAME}:${GITHUB_SHA} .
      
      # Push image to Docker Hub
      - name: Push docker image
        run: docker push ${DOCKER_IMAGE_NAME}:${GITHUB_SHA}
      
      # Update Pachyderm Pipelines
      - name: pachyderm-update-pipelines
        uses: ./pachyderm/pachyderm-github-action
        id: pup
